server {
    listen 80;
    server_name _;

    root /srv/intra-docs/current;
    index index.html;

    # Keep historical URLs:
    # /RCOS_API_DOC.html and /5gos_liuyd.html
    location / {
        try_files $uri $uri/ =404;
    }
}
